version: '3'
services:
  app:
    build: .
    ports:
      - 80:8080
    volumes:
      - ./main.py:/app/main.py
    tty: true
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_PORT=8080
      - FLASK_RUN_HOST=0.0.0.0
    command: ['flask', 'run', '--debugger', '--reload']

